# Generated by Django 3.0 on 2020-09-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_machineincident_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineincident',
            old_name='end_date',
            new_name='end_time',
        ),
    ]
