# Generated by Django 3.0 on 2020-09-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200921_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineincident',
            name='machine',
            field=models.CharField(choices=[('CHPP Fix Plant', 'CHPP Fix Plant'), ('PORT Fix Plant', 'PORT Fix Plant')], max_length=100),
        ),
    ]
